FROM node:8-alpine as builder

WORKDIR /front_app

COPY ./frontend .

RUN npm install && npm run build

FROM nginx:mainline-alpine

COPY --from=builder ./front_app/build /usr/share/nginx/html

COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

HEALTHCHECK --interval=10s --timeout=5s --retries=3 CMD curl --fail http://localhost:80/ || exit 1
